# Plugins
set -g @tpm_plugins ' \
	tmux-plugins/tpm \
	tmux-plugins/tmux-sensible \
	tmux-plugins/tmux-yank \
	dracula/tmux \
	christoomey/vim-tmux-navigator \
'

# Yank settings
set -g @yank_with_mouse off
set -g @yank_selection clipboard
unbind -T copy-mode-vi MouseDragEnd1Pane

# Status bar
set -g status-right '#(TZ="Europe/Guernsey" date +%%H:%%M:%%S)'

# Window/pane numbering
set-option -g base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Input
set -g mouse on
setw -g mode-keys vi

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
