# Plugins
set -g @tpm_plugins ' \
	tmux-plugins/tpm \
	tmux-plugins/tmux-sensible \
	dracula/tmux \
	christoomey/vim-tmux-navigator \
'

# Clipboard (vi copy-mode → xclip)
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "xclip -selection clipboard"

# Dracula settings
set -g @dracula-show-fahrenheit false

# Status bar
set -g status-right '#(TZ="Europe/Guernsey" date +%%H:%%M:%%S)'

# Window/pane numbering
set-option -g base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1

# Input
set -g mouse on
setw -g mode-keys vi
bind m run-shell 'tmux show -g mouse | grep -q "on" && tmux set -g mouse off && tmux display "Mouse: off" || { tmux set -g mouse on && tmux display "Mouse: on"; }'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
